version: "3"

services:
  webserver:
    build: webserver
    networks:
      - dev_network
    ports:
      - "7777:80"
  dbserver:
    build: dbserver
    networks:
      - dev_network
    ports:
      - "3307:3306"
    enviroment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypassword"
networks:
  dev_network: