
version: '3.1'
services:
  nginx:
    image: nginx:1.13.12-alpine
    container_name: nginx
    ports:
      - "80:80"
    expose:
      - 80
    volumes:
      - ./nginx/:/etc/nginx/conf.d/  
      - ./www/example.com/:/usr/share/nginx/html  
    depends_on:
      - nodejs
      - mysql
  nodejs:
    image: node:9.11.1-alpine
    container_name: nodejs
    environment:
      NODE_ENV: production
    working_dir: /home/app/nodejs
    volumes:
      - ./nodejs:/home/app/nodejs
    expose:
      - 3000
    ports:
      - "3000:3000"
    command: "npm start"
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mys   
  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     container_name: phpmyadmin
     ports:
        - "8080:80"
     environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test
volumes:
  my-db:
