

version: '3.1'
services:
  nginx:
    image: nginx:1.13.12-alpine
    container_name: nginx
    ports:
      - "80:80"
    expose:
      - 80
    volumes:
      - ./nginx/:/etc/nginx/conf.d/  
      - ./www/example.com/:/usr/share/nginx/html  
    depends_on:
      - nodejs
  nodejs:
    image: node:9.11.1-alpine
    container_name: nodejs
    environment:
      NODE_ENV: production
    working_dir: /home/app/nodejs
    volumes:
      - ./nodejs:/home/app/nodejs
    expose:
      - 3000
    ports:
      - "3000:3000"
    command: "npm start"
